steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t=gcr.io/${PROJECT_ID}/api:latest'
      - '-f=Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/api:latest'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'api'
      - '--image=gcr.io/${PROJECT_ID}/api:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      
images:
  - 'gcr.io/${PROJECT_ID}/api:latest'