 
name: API - Continuous Integration

on:
  repository_dispatch:
    types:
      - api-deploy-prod
  pull_request:
    branches:
      - develop
    paths:
      - "services/api/**"

env:
  WORKING_DIRECTORY: services/api
  DOCKER_LOCAL_IMAGE_TAG: corona-trace/api:latest

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: cd $WORKING_DIRECTORY && yarn --frozen-lockfile
      - name: Lint, Test, Compile
        run: cd $WORKING_DIRECTORY && yarn package
      - name: Build Docker Image
        run: cd $WORKING_DIRECTORY && docker build -t $DOCKER_LOCAL_IMAGE_TAG .