 
name: API - Continuous Integration and Deployment

on:
  repository_dispatch:
    types:
      - api-deploy-prod
  push:
    branches:
      - 'develop'
    paths:
      - "services/api/**"
      - ".github/workflows/api-cicd.yaml"

env:
  PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
  WORKING_DIRECTORY: services/api
  DOCKER_LOCAL_IMAGE_TAG: corona-trace/api:latest

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: cd $WORKING_DIRECTORY && yarn --frozen-lockfile
      - name: Lint, Test, Compile
        run: cd $WORKING_DIRECTORY && yarn package
      - name: Build Docker Image
        run: cd $WORKING_DIRECTORY && docker build -t $DOCKER_LOCAL_IMAGE_TAG .
  
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "278.0.0"
          service_account_email: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Configure gcloud CLI
        run: gcloud config set project $PROJECT_ID

      - name: Tag Docker Image
        run: docker tag $DOCKER_LOCAL_IMAGE_TAG us.gcr.io/$PROJECT_ID/api:latest

      - name: Push Docker Image to GCR
        run: docker push us.gcr.io/$PROJECT_ID/api:latest

      - name: Trigger Deployment
        run: cd $WORKING_DIRECTORY && gcloud builds submit