 
name: Matcher - Continuous Integration and Deployment

on:
  repository_dispatch:
    types:
      - matcher-deploy-prod
  push:
    branches:
      - 'develop'
    paths:
      - "services/matcher/**"
      - ".github/workflows/matcher-cicd.yaml"

env:
  PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
  WORKING_DIRECTORY: services/matcher

jobs:
  cicd:
    name: Continuous Integration and Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      - name: Install Dependencies
        run: cd $WORKING_DIRECTORY && yarn --frozen-lockfile
      
      - name: Lint, Test, Compile
        run: cd $WORKING_DIRECTORY && yarn package

      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "278.0.0"
          service_account_email: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Configure gcloud CLI
        run: gcloud config set project $PROJECT_ID

      - name: Trigger Deployment
        run: cd $WORKING_DIRECTORY && gcloud builds submit
